name: genai_labs
description: "A new Flutter project."
publish_to: "none"
version: 1.0.3+4

environment:
  sdk: ^3.12.2

dependencies:
  firebase_analytics: ^12.4.6
  firebase_crashlytics: ^5.2.7
  flutter:
    sdk: flutter

  eme_app_package:
    path: ../eme_app_package
  flutter_riverpod: ^2.6.1
  http: ^1.2.0
  image_picker: ^1.2.3
  shared_preferences: ^2.5.5
  video_player: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/
    - assets/docs/pages/
    - assets/video/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-Regular.ttf
        - asset: assets/fonts/GeistMono-Medium.ttf
          weight: 500

flutter_launcher_icons:
  ios: true
  image_path_ios: "assets/icon/logo-ios.png"
  remove_alpha_ios: true

  android: "launcher_icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  image_path_android: "assets/icon/logo.png"
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#121212"
    theme_color: "#121212"
  windows:
    generate: true
    image_path: "assets/icon/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/logo.png"

flutter_native_splash:
  color: "#121212"
  image: "assets/icon/splash.png"

  # Dark Mode Configuration
  color_dark: "#121212"
  image_dark: "assets/icon/splash.png"

  # Android 12+ Specifics
  android_12:
    image: "assets/icon/splash.png"
    image_dark: "assets/icon/splash.png"
    icon_background_color: "#121212"
    icon_background_color_dark: "#121212"

  # Platform targets
  android: true
  ios: true
  web: false
