// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPkdMHxURuWAHnKfvElakIHNf1u9zpkvk',
    appId: '1:330649053865:web:9a8b1fe6bb63cf462017b8',
    messagingSenderId: '330649053865',
    projectId: 'genai-labs-testu',
    authDomain: 'genai-labs-testu.firebaseapp.com',
    storageBucket: 'genai-labs-testu.firebasestorage.app',
    measurementId: 'G-9BFNHF04BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2eMIA-xk_uBSsfDEavkMBRsgLDOsLkXk',
    appId: '1:330649053865:android:94bbaee221d5d6ab2017b8',
    messagingSenderId: '330649053865',
    projectId: 'genai-labs-testu',
    storageBucket: 'genai-labs-testu.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtCNTzGOqyLAZN2mx0B7aP1hT_6VFcD-o',
    appId: '1:330649053865:ios:109d3560ada92a4a2017b8',
    messagingSenderId: '330649053865',
    projectId: 'genai-labs-testu',
    storageBucket: 'genai-labs-testu.firebasestorage.app',
    iosBundleId: 'world.eme.genailabs',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtCNTzGOqyLAZN2mx0B7aP1hT_6VFcD-o',
    appId: '1:330649053865:ios:109d3560ada92a4a2017b8',
    messagingSenderId: '330649053865',
    projectId: 'genai-labs-testu',
    storageBucket: 'genai-labs-testu.firebasestorage.app',
    iosBundleId: 'world.eme.genailabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPkdMHxURuWAHnKfvElakIHNf1u9zpkvk',
    appId: '1:330649053865:web:0f14643e5905d11c2017b8',
    messagingSenderId: '330649053865',
    projectId: 'genai-labs-testu',
    authDomain: 'genai-labs-testu.firebaseapp.com',
    storageBucket: 'genai-labs-testu.firebasestorage.app',
    measurementId: 'G-TS5P39MR94',
  );
}
